on: 
  push: 
    branch: 
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: User Node.js 16
      uses: actions/setup-node@v2
      with: 
        node-version: '16'

    - name: Build Project
      run: |
        npm install

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.server.youfeat.ng
        username: youfeat@youfeat.ng
        password: 9IAe8JbRFJf&
        protocol: ftps
